#######################################################################################################
#  ███    ██  █████  ████████       ██     ██ ██   ██ ██ ████████ ███████ ██      ██ ███████ ████████ #
#  ████   ██ ██   ██    ██          ██     ██ ██   ██ ██    ██    ██      ██      ██ ██         ██    #
#  ██ ██  ██ ███████    ██    █████ ██  █  ██ ███████ ██    ██    █████   ██      ██ ███████    ██    #
#  ██  ██ ██ ██   ██    ██          ██ ███ ██ ██   ██ ██    ██    ██      ██      ██      ██    ██    #
#  ██   ████ ██   ██    ██           ███ ███  ██   ██ ██    ██    ███████ ███████ ██ ███████    ██    #
#######################################################################################################
# Made by Nat0uille & Love                                                                            #
#######################################################################################################

# Version of the config file.
config-version: 1.0

# Language of the plugin (en-us / fr-fr)
lang: en-us

database:
  # Type: MySQL / MariaDB
  type: "MySQL"
  host: "localhost"
  port: 3306
  database: "nat_whitelist"
  username: ""
  password: ""

discord-bot-token: ""
